version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
    - build-and-test

orbs:
  codecov: codecov/codecov@1.0.2


jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenium/standalone-chrome
        environment:
          port: 4444:4444

    steps:
      - checkout
      - run: mvn clean cobertura:cobertura -Dremote=true
      - store_test_results:
          path: target/surefire-reports
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

